"""BigQuery Database Module for Alaska Department of Snow (ADS).

Provides client logic for dataset creation, schema setup, and row insertion
for the Unstructured Document Synthesis operational pipeline.
"""

from datetime import datetime, timezone
import json
import os
from typing import Any, Dict, List, Optional, Union
import uuid

from google.api_core.exceptions import GoogleAPICallError
from google.cloud import bigquery

from logger import get_logger

logger = get_logger("ads_database")

DATASET_NAME = "ads_operations"
TABLE_NAME = "synthesis_logs"
CHAT_TABLE_NAME = "chat_logs"

SYNTHESIS_LOGS_SCHEMA = [
    bigquery.SchemaField("synthesis_id", "STRING", mode="REQUIRED", description="Unique identifier for the synthesis job"),
    bigquery.SchemaField("timestamp", "TIMESTAMP", mode="REQUIRED", description="Timestamp when synthesis was logged"),
    bigquery.SchemaField("document_name", "STRING", mode="REQUIRED", description="Original document or PDF file name"),
    bigquery.SchemaField("operational_summary", "STRING", mode="NULLABLE", description="Synthesized operational summary"),
    bigquery.SchemaField("structured_payload", "JSON", mode="NULLABLE", description="Structured JSON payload"),
    bigquery.SchemaField("risk_assessment_level", "STRING", mode="NULLABLE", description="Risk level (LOW, MEDIUM, HIGH, CRITICAL)"),
    bigquery.SchemaField("sanitization_status", "STRING", mode="NULLABLE", description="Sanitization status (PASSED, FLAGGED, BLOCKED, SANITIZED)"),
    bigquery.SchemaField("log_history", "STRING", mode="NULLABLE", description="Audit trail and processing history"),
]

CHAT_LOGS_SCHEMA = [
    bigquery.SchemaField("session_id", "STRING", mode="REQUIRED", description="Unique identifier for the chat session"),
    bigquery.SchemaField("timestamp", "TIMESTAMP", mode="REQUIRED", description="Timestamp of the message turn"),
    bigquery.SchemaField("document_name", "STRING", mode="NULLABLE", description="Name of the grounded operational document"),
    bigquery.SchemaField("user_query", "STRING", mode="NULLABLE", description="User prompt or question"),
    bigquery.SchemaField("bot_response", "STRING", mode="NULLABLE", description="Sanitized response generated by Gemini or security alert"),
    bigquery.SchemaField("model_armor_flagged", "BOOLEAN", mode="NULLABLE", description="True if flagged or blocked by Model Armor"),
    bigquery.SchemaField("chat_id", "STRING", mode="NULLABLE", description="Unique identifier for the chat turn"),
    bigquery.SchemaField("user_message", "STRING", mode="NULLABLE", description="User prompt (alias for user_query)"),
    bigquery.SchemaField("model_response", "STRING", mode="NULLABLE", description="Model response (alias for bot_response)"),
    bigquery.SchemaField("sanitization_status", "STRING", mode="NULLABLE", description="Security status: PASSED, BLOCKED, FLAGGED"),
    bigquery.SchemaField("violations", "STRING", mode="NULLABLE", description="Security violations detected if blocked"),
    bigquery.SchemaField("log_history", "STRING", mode="NULLABLE", description="Audit history of security checks and model execution"),
]


def get_bigquery_client(project_id: Optional[str] = None) -> bigquery.Client:
    """Initializes and returns a BigQuery client.

    Args:
        project_id: Google Cloud project ID. If omitted, uses environment variables.

    Returns:
        bigquery.Client instance.
    """
    proj = project_id or os.environ.get("PROJECT_ID") or os.environ.get("GOOGLE_CLOUD_PROJECT")
    return bigquery.Client(project=proj)


def init_database(
    project_id: Optional[str] = None,
    dataset_id: str = DATASET_NAME,
    table_id: str = TABLE_NAME,
    location: str = "US",
    schema_sql_path: Optional[str] = None,
) -> None:
    """Ensures BigQuery dataset and synthesis_logs table exist with the required schema.

    Args:
        project_id: Target GCP project ID.
        dataset_id: BigQuery dataset name.
        table_id: BigQuery table name.
        location: Geographic location for the dataset.
        schema_sql_path: Optional path to schema.sql to execute DDL directly.
    """
    client = get_bigquery_client(project_id=project_id)
    project = client.project

    logger.info(
        f"Initializing BigQuery database for project '{project}', dataset '{dataset_id}'",
        extra={"project_id": project, "dataset_id": dataset_id, "location": location},
    )

    # Option 1: Execute schema.sql if provided and exists
    if schema_sql_path and os.path.exists(schema_sql_path):
        try:
            with open(schema_sql_path, "r", encoding="utf-8") as f:
                ddl = f.read()
            logger.info(f"Executing DDL from SQL file: {schema_sql_path}")
            query_job = client.query(ddl, location=location)
            query_job.result()
            logger.info("Successfully executed DDL schema script.")
            return
        except Exception as e:
            logger.warning(
                f"SQL DDL execution encountered an issue ({e}). Proceeding with programmatic schema creation."
            )

    # Option 2: Programmatic dataset and table creation using BigQuery SDK
    full_dataset_ref = f"{project}.{dataset_id}"
    dataset = bigquery.Dataset(full_dataset_ref)
    dataset.location = location
    dataset.description = "Operational document synthesis and log records for Alaska Department of Snow"

    client.create_dataset(dataset, exists_ok=True)
    logger.info(f"Dataset '{full_dataset_ref}' verified/created.")

    full_table_ref = f"{project}.{dataset_id}.{table_id}"
    table = bigquery.Table(full_table_ref, schema=SYNTHESIS_LOGS_SCHEMA)
    table.description = "Audit logs and operational synthesis outputs for winter storm response operations"

    client.create_table(table, exists_ok=True)
    logger.info(f"Table '{full_table_ref}' verified/created with required schema.")

    chat_table_ref = f"{project}.{dataset_id}.{CHAT_TABLE_NAME}"
    chat_table = bigquery.Table(chat_table_ref, schema=CHAT_LOGS_SCHEMA)
    chat_table.description = "Audit logs and conversation records for document-grounded operator chats"
    client.create_table(chat_table, exists_ok=True)
    logger.info(f"Table '{chat_table_ref}' verified/created with required schema.")


def insert_synthesis_log(
    document_name: str,
    operational_summary: Optional[str] = None,
    structured_payload: Optional[Union[Dict[str, Any], List[Any], str]] = None,
    risk_assessment_level: str = "LOW",
    sanitization_status: str = "PASSED",
    log_history: str = "",
    synthesis_id: Optional[str] = None,
    timestamp: Optional[Union[datetime, str]] = None,
    project_id: Optional[str] = None,
    dataset_id: str = DATASET_NAME,
    table_id: str = TABLE_NAME,
) -> Dict[str, Any]:
    """Inserts a document synthesis record into BigQuery synthesis_logs.

    Args:
        document_name: Name of the processed operational PDF or document.
        operational_summary: Synthesized executive summary.
        structured_payload: JSON dict, list, or serialized string of structured parameters.
        risk_assessment_level: Assessed risk level ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL').
        sanitization_status: Security check status ('PASSED', 'FLAGGED', 'BLOCKED', 'SANITIZED').
        log_history: Detailed audit and processing notes.
        synthesis_id: Optional unique identifier. Generated via UUID if not provided.
        timestamp: Optional timestamp. Defaults to UTC now.
        project_id: Target GCP project ID.
        dataset_id: Target BigQuery dataset name.
        table_id: Target BigQuery table name.

    Returns:
        The inserted row dictionary.

    Raises:
        RuntimeError: If row insertion fails.
    """
    client = get_bigquery_client(project_id=project_id)
    project = client.project
    full_table_ref = f"{project}.{dataset_id}.{table_id}"

    record_id = synthesis_id or f"synth-{uuid.uuid4()}"

    if timestamp is None:
        ts_value = datetime.now(timezone.utc).isoformat()
    elif isinstance(timestamp, datetime):
        if timestamp.tzinfo is None:
            ts_value = timestamp.replace(tzinfo=timezone.utc).isoformat()
        else:
            ts_value = timestamp.isoformat()
    else:
        ts_value = str(timestamp)

    # Serialize structured_payload to JSON string if provided as dict or list
    if isinstance(structured_payload, (dict, list)):
        payload_str = json.dumps(structured_payload)
    elif structured_payload is None:
        payload_str = None
    else:
        payload_str = str(structured_payload)

    row = {
        "synthesis_id": record_id,
        "timestamp": ts_value,
        "document_name": document_name,
        "operational_summary": operational_summary or "",
        "structured_payload": payload_str,
        "risk_assessment_level": risk_assessment_level,
        "sanitization_status": sanitization_status,
        "log_history": log_history,
    }

    try:
        errors = client.insert_rows_json(full_table_ref, [row])
        if errors:
            logger.error(
                f"Failed to insert row into {full_table_ref}",
                extra={"errors": errors, "synthesis_id": record_id},
            )
            raise RuntimeError(f"BigQuery insert_rows_json errors: {errors}")

        logger.info(
            f"Successfully inserted synthesis record '{record_id}' into '{full_table_ref}'",
            extra={
                "synthesis_id": record_id,
                "document_name": document_name,
                "sanitization_status": sanitization_status,
                "risk_assessment_level": risk_assessment_level,
            },
        )
        return row
    except GoogleAPICallError as e:
        logger.error(f"Google API call error during insertion: {e}", extra={"synthesis_id": record_id})
        raise


def get_synthesis_log(
    synthesis_id: str,
    project_id: Optional[str] = None,
    dataset_id: str = DATASET_NAME,
    table_id: str = TABLE_NAME,
) -> Optional[Dict[str, Any]]:
    """Retrieves a synthesis record by its synthesis_id.

    Args:
        synthesis_id: Unique identifier of the record.
        project_id: GCP project ID.
        dataset_id: Dataset name.
        table_id: Table name.

    Returns:
        Row dictionary or None if not found.
    """
    client = get_bigquery_client(project_id=project_id)
    project = client.project
    query = f"""
        SELECT synthesis_id, timestamp, document_name, operational_summary,
               structured_payload, risk_assessment_level, sanitization_status, log_history
        FROM `{project}.{dataset_id}.{table_id}`
        WHERE synthesis_id = @synthesis_id
        LIMIT 1
    """
    job_config = bigquery.QueryJobConfig(
        query_parameters=[bigquery.ScalarQueryParameter("synthesis_id", "STRING", synthesis_id)]
    )
    results = list(client.query(query, job_config=job_config).result())
    if not results:
        return None
    return dict(results[0].items())


def log_chat_message(
    session_id: str,
    user_query: str,
    bot_response: str,
    document_name: Optional[str] = None,
    model_armor_flagged: bool = False,
    chat_id: Optional[str] = None,
    sanitization_status: Optional[str] = None,
    violations: Optional[Union[List[str], str]] = None,
    log_history: str = "",
    timestamp: Optional[Union[datetime, str]] = None,
    project_id: Optional[str] = None,
    dataset_id: str = DATASET_NAME,
    table_id: str = CHAT_TABLE_NAME,
) -> Dict[str, Any]:
    """Inserts an individual chat turn into BigQuery chat_logs.

    Args:
        session_id: Unique identifier for the multi-turn session.
        user_query: User prompt, question, or input text.
        bot_response: Model generated response or security alert message.
        document_name: Name of the grounded operational document.
        model_armor_flagged: Boolean indicating if Model Armor flagged or blocked the message.
        chat_id: Unique turn ID (UUID generated if omitted).
        sanitization_status: Security status (e.g. PASSED, BLOCKED, FLAGGED).
        violations: List or string of security policy violations.
        log_history: Pipeline execution audit notes.
        timestamp: Event timestamp.
        project_id: Target GCP project ID.
        dataset_id: BigQuery dataset name.
        table_id: BigQuery table name.

    Returns:
        The inserted row dictionary.
    """
    client = get_bigquery_client(project_id=project_id)
    project = client.project
    full_table_ref = f"{project}.{dataset_id}.{table_id}"

    turn_id = chat_id or f"chat-{uuid.uuid4()}"
    ts_val = timestamp or datetime.now(timezone.utc).isoformat()
    if isinstance(ts_val, datetime):
        ts_val = ts_val.isoformat()

    status_str = sanitization_status or ("BLOCKED" if model_armor_flagged else "PASSED")
    violations_str = json.dumps(violations) if isinstance(violations, (list, dict)) else str(violations or "")

    row = {
        "session_id": session_id,
        "timestamp": ts_val,
        "document_name": document_name,
        "user_query": user_query,
        "bot_response": bot_response,
        "model_armor_flagged": bool(model_armor_flagged),
        # Compatible audit fields
        "chat_id": turn_id,
        "user_message": user_query,
        "model_response": bot_response,
        "sanitization_status": status_str,
        "violations": violations_str,
        "log_history": log_history,
    }

    try:
        errors = client.insert_rows_json(full_table_ref, [row])
        if errors:
            logger.error(
                f"Failed to insert chat row into {full_table_ref}",
                extra={"errors": errors, "chat_id": turn_id, "session_id": session_id},
            )
            raise RuntimeError(f"BigQuery insert_rows_json errors: {errors}")

        logger.info(
            f"Successfully inserted chat record '{turn_id}' into '{full_table_ref}'",
            extra={
                "chat_id": turn_id,
                "session_id": session_id,
                "model_armor_flagged": model_armor_flagged,
                "sanitization_status": status_str,
            },
        )
        return row
    except GoogleAPICallError as e:
        logger.error(f"Google API call error during chat log insertion: {e}", extra={"chat_id": turn_id})
        raise


def insert_chat_log(
    session_id: str,
    user_message: str,
    model_response: str,
    document_name: Optional[str] = None,
    sanitization_status: str = "PASSED",
    violations: Optional[Union[List[str], str]] = None,
    log_history: str = "",
    chat_id: Optional[str] = None,
    timestamp: Optional[Union[datetime, str]] = None,
    project_id: Optional[str] = None,
    dataset_id: str = DATASET_NAME,
    table_id: str = CHAT_TABLE_NAME,
) -> Dict[str, Any]:
    """Compatibility wrapper that delegates to log_chat_message."""
    model_armor_flagged = sanitization_status in ("BLOCKED", "FLAGGED")
    return log_chat_message(
        session_id=session_id,
        user_query=user_message,
        bot_response=model_response,
        document_name=document_name,
        model_armor_flagged=model_armor_flagged,
        chat_id=chat_id,
        sanitization_status=sanitization_status,
        violations=violations,
        log_history=log_history,
        timestamp=timestamp,
        project_id=project_id,
        dataset_id=dataset_id,
        table_id=table_id,
    )


def get_chat_logs(
    session_id: str,
    project_id: Optional[str] = None,
    dataset_id: str = DATASET_NAME,
    table_id: str = CHAT_TABLE_NAME,
    limit: int = 50,
) -> List[Dict[str, Any]]:
    """Retrieves all chat turns for a given session_id ordered by timestamp.

    Args:
        session_id: Session identifier.
        project_id: GCP project ID.
        dataset_id: Dataset name.
        table_id: Table name.
        limit: Max turns to fetch.

    Returns:
        List of row dicts.
    """
    client = get_bigquery_client(project_id=project_id)
    project = client.project
    query = f"""
        SELECT chat_id, session_id, timestamp, document_name, user_message,
               model_response, sanitization_status, violations, log_history
        FROM `{project}.{dataset_id}.{table_id}`
        WHERE session_id = @session_id
        ORDER BY timestamp ASC
        LIMIT @limit
    """
    job_config = bigquery.QueryJobConfig(
        query_parameters=[
            bigquery.ScalarQueryParameter("session_id", "STRING", session_id),
            bigquery.ScalarQueryParameter("limit", "INT64", limit),
        ]
    )
    results = list(client.query(query, job_config=job_config).result())
    return [dict(r.items()) for r in results]


if __name__ == "__main__":
    init_database()
