-- Schema Initialization for Alaska Department of Snow (ADS)
-- Unstructured Document Synthesis Storage Setup
-- Dataset: ads_operations
-- Table: synthesis_logs

CREATE SCHEMA IF NOT EXISTS `ads_operations`
OPTIONS (
    description = "Operational document synthesis and log records for Alaska Department of Snow",
    location = "US"
);

CREATE TABLE IF NOT EXISTS `ads_operations.synthesis_logs` (
    synthesis_id STRING NOT NULL OPTIONS(description="Unique identifier for the document synthesis job"),
    timestamp TIMESTAMP NOT NULL OPTIONS(description="Timestamp when document synthesis was recorded"),
    document_name STRING NOT NULL OPTIONS(description="Original operational document or PDF file name"),
    operational_summary STRING OPTIONS(description="Synthesized operational summary of the document"),
    structured_payload JSON OPTIONS(description="Structured JSON payload containing extracted operational parameters"),
    risk_assessment_level STRING OPTIONS(description="Assessed risk level: LOW, MEDIUM, HIGH, or CRITICAL"),
    sanitization_status STRING OPTIONS(description="Sanitization status from Model Armor / DLP checks (PASSED, FLAGGED, BLOCKED, SANITIZED)"),
    log_history STRING OPTIONS(description="Audit trail, security scan notes, and processing history for the pipeline")
)
OPTIONS (
    description = "Audit logs and operational synthesis outputs for winter storm response operations"
);

CREATE TABLE IF NOT EXISTS `ads_operations.chat_logs` (
    session_id STRING NOT NULL OPTIONS(description="Unique identifier for the chat session"),
    timestamp TIMESTAMP NOT NULL OPTIONS(description="Timestamp of the message turn"),
    document_name STRING OPTIONS(description="Name of the grounded operational document"),
    user_query STRING NOT NULL OPTIONS(description="User prompt or question"),
    bot_response STRING NOT NULL OPTIONS(description="Sanitized response generated by Gemini or security alert"),
    model_armor_flagged BOOLEAN NOT NULL OPTIONS(description="True if flagged or blocked by Model Armor"),
    chat_id STRING OPTIONS(description="Unique identifier for the chat turn"),
    user_message STRING OPTIONS(description="User message alias for user_query"),
    model_response STRING OPTIONS(description="Model response alias for bot_response"),
    sanitization_status STRING OPTIONS(description="Security status: PASSED, BLOCKED, FLAGGED"),
    violations STRING OPTIONS(description="Security violations detected if blocked"),
    log_history STRING OPTIONS(description="Audit history of security checks and model execution")
)
OPTIONS (
    description = "Audit logs and conversation records for document-grounded operator chats"
);

